# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('note_date', models.DateTimeField(verbose_name='Session Date')),
                ('note_vid', models.CharField(max_length=100)),
            ],
        ),
    ]
