# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_instructor',
            field=models.TextField(null=True, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='notes',
            name='note_title',
            field=models.TextField(null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_text',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_vid',
            field=models.CharField(max_length=100, null=True, verbose_name='Video Link'),
        ),
    ]
